### PR TITLE
Use POST method for heatmap loading if URL is too long

### LINKED ISSUE #69: Heatmap URL too long due to fragmented ranges
* Release number or git hash: 6b12ca0bacb90ee0f3030159e57f21bd2b7ef037
* Web browser version and OS: Chrome 76
* Environment (local or deployed): Linux

### Steps to reproduce

1. Open the following [TACO URL](https://taco.caleydoapp.org/api/dataset/matrix/tcgaGbm20130222Mrna/data?format=png&range=(0%3A2%2C3%2C12%2C14%3A18%2C19%3A22%2C24%3A32%2C37%3A39%2C43%2C45%2C46%2C49%2C50%3A52%2C73%2C83%2C85%2C88%2C89%3A91%2C96%2C101%2C102%3A104%2C105%2C108%2C110%3A112%2C113%3A115%2C119%2C122%2C123%2C127%2C128%2C133%2C137%3A141%2C142%3A145%2C146%2C148%2C158%2C160%2C162%2C165%3A168%2C169%3A171%2C177%2C183%2C185%3A187%2C189%2C191%2C203%2C207%2C209%2C215%2C227%2C233%2C241%3A243%2C248%3A252%2C253%2C260%2C267%2C268%3A270%2C277%3A282%2C287%2C291%2C292%2C296%2C297%2C299%2C300%2C320%2C321%3A323%2C325%2C329%2C335%3A337%2C340%2C350%2C353%3A355%2C369%2C372%2C374%2C384%2C388%2C392%2C395%2C400%2C406%2C411%2C416%2C427%3A429%2C430%2C441%2C443%2C445%2C449%3A452%2C457%3A459%2C460%2C462%2C465%2C467%2C470%2C479%2C483%3A486%2C487%3A489%2C490%3A492%2C493%2C496%2C497%2C500%2C508%3A511%2C523%3A525%2C2%2C4%2C5%3A8%2C9%2C11%2C13%2C18%2C22%2C23%2C33%2C36%2C48%2C53%2C55%2C58%2C60%2C61%2C66%2C74%3A76%2C84%2C86%2C126%2C129%2C156%2C161%2C163%3A165%2C171%2C174%2C178%2C187%2C188%2C196%2C204%2C210%2C213%2C217%2C223%2C225%2C234%2C256%2C261%2C265%2C274%2C285%3A287%2C305%2C309%2C310%2C313%2C319%2C330%2C332%3A334%2C341%3A344%2C347%3A350%2C351%2C357%2C358%2C363%2C367%2C389%2C390%2C401%2C412%2C423%2C424%3A427%2C439%3A441%2C452%2C466%2C468%3A470%2C471%3A473%2C477%2C494%2C502%2C511%2C516%2C518%2C519%3A522%2C525%2C8%2C10%2C32%2C34%3A36%2C40%2C47%2C52%2C57%2C59%2C62%2C63%3A66%2C72%2C76%2C77%2C87%2C91%3A93%2C99%2C106%2C109%2C112%2C115%2C116%2C132%2C134%3A136%2C145%2C147%2C150%2C157%2C159%2C172%2C173%2C175%2C179%3A183%2C198%3A203%2C206%2C211%2C212%2C216%2C220%2C222%2C224%2C235%3A240%2C243%2C246%2C252%2C254%2C255%2C257%2C259%2C262%3A265%2C270%3A272%2C273%2C275%2C276%2C282%2C288%2C290%2C294%2C295%2C298%2C302%2C306%2C307%2C311%2C312%2C315%2C316%3A319%2C323%3A325%2C326%2C331%2C334%2C338%2C346%2C355%2C359%2C361%2C370%2C373%2C375%3A377%2C378%2C381%2C383%2C385%2C391%2C394%2C396%3A400%2C402%2C404%2C405%2C407%2C408%3A411%2C413%3A415%2C417%3A419%2C420%2C422%2C429%2C431%2C433%2C435%2C436%2C442%2C444%2C448%2C453%2C455%2C456%2C473%2C474%3A477%2C480%3A482%2C486%2C489%2C492%2C495%2C501%2C504%2C507%2C513%3A516%2C517%2C526%2C527%2C39%2C41%3A43%2C44%2C54%2C56%2C67%2C68%3A72%2C78%3A83%2C93%3A96%2C97%3A99%2C100%2C104%2C107%2C117%2C118%2C120%2C121%2C124%2C125%2C130%2C131%2C136%2C141%2C149%2C151%2C152%3A156%2C168%2C176%2C184%2C190%2C192%2C193%3A196%2C197%2C205%2C208%2C214%2C218%3A220%2C221%2C226%2C228%3A233%2C240%2C244%2C245%2C247%2C258%2C266%2C272%2C283%2C284%2C289%2C293%2C301%2C303%3A305%2C308%2C314%2C327%3A329%2C337%2C339%2C344%3A346%2C352%2C356%2C360%2C362%2C364%2C365%3A367%2C368%2C371%2C377%2C379%2C380%2C382%2C386%3A388%2C393%2C403%2C415%2C419%2C421%2C432%2C434%2C437%2C438%2C446%2C447%2C454%2C459%2C461%2C463%2C464%2C478%2C482%2C498%2C499%2C503%2C505%3A507%2C512%2C522)%2C(11772%2C8709%2C2723%2C10376%2C659%2C6549%2C2586%2C9532%2C8477%2C1710%2C9205%2C5517%2C7151%2C5857%2C1891%2C10190%2C5024%2C10275%2C5626%2C7818%2C9850%2C1273%2C8717%2C7277%2C10394%2C11409%2C11404%2C2428%2C267%2C10924%2C7545%2C9334%2C3549%2C1412%2C5827%2C10202%2C5146%2C4762%2C11608%2C9294%2C7637%2C6907%2C7058%2C4133%2C6445%2C2736%2C1560%2C631%2C4293%2C2562%2C8587%2C2628%2C3403%2C10807%2C1844%2C8176%2C3845%2C9231%2C6778%2C3751%2C5335%2C9142%2C1425%2C7566%2C6929%2C939%2C9621%2C11761%2C11558%2C1304%2C11255%2C1856%2C10917%2C4910%2C6691%2C854%2C7395%2C3779%2C1431%2C7945%2C5982%2C1576%2C8584%2C10876%2C3162%2C2247%2C3848%2C8227%2C11626%2C6324%2C1485%2C9544%2C2383%2C11221%2C4428%2C8220%2C10677%2C495%2C9567%2C3982%2C11052%2C7825%2C1604%2C5153%2C738%2C11670%2C3089%2C11514%2C8702%2C9331%2C678%2C841%2C6228%2C5757%2C3908%2C6555%2C11273%2C1215%2C2462%2C1508%2C4158%2C1389%2C11586%2C1192%2C3901%2C3598%2C11482%2C8004%2C2890%2C5228%2C1956%2C5904%2C8660%2C7056%2C7434%2C6183%2C8095%2C2223%2C11510%2C4971%2C10933%2C3297%2C9666%2C9210%2C3272%2C2479%2C4115%2C2114%2C9806%2C7847%2C7346%2C2246%2C2422%2C4310%2C3399%2C4525%2C9462%2C6589%2C6469%2C3438%2C10928%2C2747%2C8769%2C8648%2C1607%2C2201%2C113%2C10459%2C6632%2C10022%2C12028%2C6971%2C1245%2C11331%2C5091%2C10302%2C5389%2C647%2C5818%2C9619%2C7708%2C935%2C3864%2C5185%2C3769%2C7629%2C7167%2C990%2C5121%2C8567%2C3380%2C10034%2C1268%2C10809%2C2416%2C5237%2C1595%2C5713%2C4301%2C4011%2C4452%2C5691%2C11093%2C7533%2C5600%2C9070%2C11883%2C6280%2C6421%2C3091%2C8009%2C2179%2C542%2C11621%2C2204%2C1380%2C1478%2C7103%2C4194%2C3856%2C2860%2C10379%2C10682%2C6618%2C6928%2C5715%2C3213%2C7327%2C4223%2C8564%2C4105%2C11270%2C6749%2C1035%2C8395%2C5004%2C10791%2C11528%2C9321%2C8474%2C3217%2C5252%2C8060%2C2663%2C7278%2C7180%2C6904%2C7384%2C7129%2C11256%2C7701%2C11259%2C8274%2C5450%2C4962%2C114%2C618%2C2666%2C11878%2C3587%2C2050%2C2316%2C2919%2C7938%2C11908%2C8257%2C2848%2C6685%2C1573%2C10654%2C4732%2C1765%2C9661%2C6264%2C9690%2C1608%2C3357%2C345%2C7530%2C4144%2C7018%2C11315%2C409%2C6470%2C2319%2C7305%2C11786%2C2170%2C2918%2C6064%2C4364%2C9220%2C8698%2C6523%2C3314%2C2064%2C8944%2C10614%2C1890%2C7485%2C8731%2C7588%2C2758%2C72%2C9312%2C7745%2C8439%2C7354%2C11092%2C3319%2C11977%2C11800%2C7946%2C9728%2C3792%2C7547%2C8193%2C5109%2C3539%2C4251%2C8826%2C4605%2C7947%2C11284%2C6309%2C8544%2C6146%2C3600%2C2962%2C9095%2C9098%2C11965%2C7288%2C8679%2C3353%2C5838%2C8668%2C51%2C4953%2C863%2C1306%2C421%2C5856%2C4146%2C3691%2C49%2C7366%2C6954%2C3127%2C9064%2C853%2C6203%2C6694%2C8070%2C2382%2C8793%2C2535%2C7019%2C1067%2C6010%2C1600%2C1593%2C10257%2C8040%2C3899%2C11973%2C7914%2C692%2C5008%2C680%2C993%2C2766%2C2177%2C9657%2C6977%2C5090%2C9789%2C11529%2C3012%2C8756%2C11641%2C296%2C3130%2C7097%2C9181%2C9586%2C832%2C5198%2C2005%2C6174%2C9951%2C2567%2C11162%2C4049%2C6282%2C3501%2C8037%2C7433%2C6312%2C4823%2C7808%2C11750%2C9388%2C3711%2C11019%2C11733%2C6443%2C6665%2C8956%2C6926%2C3006%2C3141%2C11497%2C193%2C11968%2C176%2C8792%2C8152%2C9620%2C2233%2C5570%2C10422%2C9726%2C9279%2C1990%2C11067%2C5599%2C8021%2C10343%2C281%2C10980%2C4303%2C4895%2C6530%2C10539%2C11899%2C11912%2C9410%2C4539%2C3384%2C9027%2C11444%2C8171%2C2118%2C9208%2C5341%2C7289%2C2986%2C5954%2C8708%2C6209%2C2530%2C10064%2C10296%2C4492%2C8886%2C8075%2C3278%2C3893%2C3440%2C716%2C11101%2C5177%2C9805%2C11225%2C5621%2C9581%2C5489%2C11700%2C11483%2C4519%2C3377%2C2305%2C8239%2C4472%2C8771%2C10869%2C1929%2C8514%2C11024%2C5892%2C8420%2C6806%2C6697%2C7881%2C366%2C10150%2C1711%2C9969%2C822%2C9001%2C480%2C8531%2C11635%2C7754%2C3407%2C5115%2C653%2C9019%2C5919%2C135%2C7177%2C8088%2C600%2C1982%2C5127%2C4646%2C6781%2C2741%2C6531%2C7479%2C3446%2C8875%2C2642%2C3392%2C11208%2C4927%2C10815%2C1501%2C6331%2C8845%2C2025%2C3911%2C9675%2C6273%2C4305%2C10717%2C11212%2C1780%2C3975%2C435%2C10992%2C3759%2C6591%2C1464%2C10231%2C10191%2C4035%2C128%2C3076%2C11300%2C1741%2C7595%2C5837%2C6847%2C9820%2C5923%2C240%2C11649%2C646%2C11891%2C5311%2C5511%2C7564%2C6367%2C11858%2C1963%2C9315%2C3057%2C5730%2C10348%2C2675%2C7603%2C3311%2C5798%2C11931%2C3439%2C1314%2C10013%2C2359%2C4191%2C9399%2C5815%2C10080%2C926%2C9342%2C1702%2C5732%2C5473%2C5536%2C6836%2C9379%2C9303%2C2152%2C10545%2C936%2C2404%2C8136%2C5802%2C7926%2C8938%2C5903%2C4240%2C4598%2C436%2C3833%2C2339%2C11904%2C2126%2C5488%2C2997%2C4618%2C11847%2C4906%2C10423%2C493%2C7092%2C2205%2C894%2C4821%2C8749%2C10731%2C5741%2C6556%2C104%2C11096%2C4839%2C7633%2C736%2C5431%2C4351%2C2808%2C1203%2C1294%2C9925%2C3923%2C5601%2C6501%2C1328%2C2563%2C4273%2C8348%2C11294%2C1547%2C9712%2C1495%2C11283%2C6427%2C10331%2C10652%2C6075%2C10140%2C4995%2C10579%2C8585%2C1091%2C11911%2C10832%2C3609%2C6163%2C1056%2C5787%2C8596%2C6655%2C1090%2C1341%2C2110%2C1649%2C7333%2C4117%2C1367%2C2200%2C5151%2C10314%2C968%2C5861%2C8212%2C7306%2C904%2C1853%2C8715%2C8962%2C7715%2C9129%2C10116%2C2620%2C4797%2C11979%2C5993%2C7330%2C1456%2C4639%2C2401%2C1316%2C7299%2C701%2C3442%2C5283%2C10159%2C7237%2C6579%2C9736%2C1545%2C10994%2C3737%2C5071%2C5816%2C2299%2C9075%2C3999%2C9600%2C5656%2C5143%2C7877%2C3410%2C1668%2C10831%2C11108%2C1059%2C5625%2C3209%2C10072%2C2193%2C8779%2C2721%2C3789%2C3970%2C8206%2C731%2C3251%2C5382%2C11115%2C9146%2C9485%2C5271%2C5944%2C9427%2C10566%2C1934%2C10060%2C9721%2C207%2C11540%2C8149%2C4668%2C1699%2C10953%2C3855%2C9760%2C1707%2C2335%2C9398%2C11754%2C8181%2C8392%2C9894%2C11960%2C10974%2C8758%2C9283%2C569%2C8645%2C10167%2C5521%2C5025%2C3239%2C7140%2C7599%2C2487%2C11578%2C1044%2C9755%2C937%2C4529%2C3767%2C3917%2C3889%2C768%2C5547%2C9655%2C5414%2C2536%2C8985%2C9680%2C3900%2C4737%2C9317%2C3020%2C48%2C8237%2C11342%2C7081%2C11759%2C10487%2C4770%2C4069%2C265%2C4337%2C9913%2C6612%2C10028%2C5053%2C8096%2C511%2C4530%2C1135%2C6766%2C8110%2C9852%2C9343%2C9305%2C12013%2C3503%2C10108%2C1539%2C4029%2C508%2C9372%2C10194%2C7166%2C4464%2C2906%2C1897%2C6365%2C2096%2C4774%2C1520%2C6583%2C4629%2C3871%2C1269%2C786%2C7246%2C2458%2C5131%2C1802%2C6142%2C2681%2C4016%2C2988%2C9930%2C2116%2C9341%2C2288%2C4382%2C38%2C11687%2C10921%2C6096%2C8155%2C9213%2C1250%2C2117%2C3126%2C9077%2C2613%2C4228%2C5526%2C2775%2C1992%2C7374%2C6727%2C1150%2C8214%2C119%2C11555%2C2671%2C749%2C10321%2C2347%2C445%2C8271%2C652%2C10272%2C2187%2C3260%2C8289%2C172%2C5060%2C3713%2C8807%2C7205%2C7297%2C11502%2C5977%2C3146%2C1117%2C5707%2C6316%2C6208%2C9568%2C3657%2C570%2C252%2C6487%2C11943%2C6067%2C6805%2C1236%2C8666%2C9376%2C6276%2C548%2C781%2C7990%2C8506%2C9800%2C6803%2C10977%2C2490%2C4311%2C708%2C1534%2C10256%2C3983%2C7578%2C3948%2C735%2C3497%2C6094%2C2992%2C8373%2C6664%2C886%2C4926%2C6259%2C5157%2C2977%2C10997%2C1642%2C16%2C9866%2C7014%2C11791%2C8991%2C3788%2C1410%2C1120%2C1395%2C11140%2C833%2C11405%2C5039%2C11099%2C1886%2C3599%2C10801%2C3137%2C11704%2C7611%2C2868%2C3072%2C9361%2C10858%2C10602%2C4825%2C10253%2C4950%2C9986%2C298%2C11083%2C5953%2C6944%2C10304%2C2105%2C8776%2C9703%2C3806%2C9043%2C11709%2C2481%2C5563%2C903%2C8669%2C9961%2C449%2C7128%2C10550%2C5408%2C9310%2C1704%2C2912%2C4518%2C9131%2C2943%2C163%2C7030%2C11226%2C10488%2C10029%2C11632%2C604%2C1270%2C6620%2C5101%2C2035%2C9097%2C3839%2C721%2C10375%2C3184%2C5725%2C3366%2C8434%2C5524%2C2293%2C4989%2C7188%2C9049%2C2715%2C10222%2C8483%2C9392%2C6597%2C2080%2C6951%2C8606%2C11048%2C8356%2C777%2C6047%2C1797%2C5291%2C4533%2C10860%2C4045%2C8943%2C4932%2C7231%2C8959%2C1325%2C3004%2C167%2C9768%2C9630%2C8357%2C4968%2C5947%2C900%2C8454%2C11037%2C7977%2C5968%2C883%2C7961%2C5568%2C1409%2C1824%2C255%2C1237%2C10568%2C7206%2C3187%2C6001%2C9438%2C3828%2C4066%2C10512%2C3870%2C481%2C9265%2C3432%2C4198%2C1563%2C5949%2C4355%2C11190%2C10519%2C6771%2C7794%2C7471%2C9693%2C5047%2C2391%2C10465%2C4645%2C8290%2C4591%2C4339%2C9407%2C6256%2C919%2C10365%2C4114%2C2709%2C9761%2C4445%2C7192%2C11383%2C5385%2C2738%2C2847%2C8464%2C3854%2C225%2C6690%2C5527%2C10897%2C8068%2C8574%2C11441%2C964%2C7435%2C7093%2C8829%2C11243%2C11332%2C4005%2C5002%2C6071%2C2955%2C6745%2C4458%2C217%2C507%2C2393%2C11808%2C3880%2C6268%2C7623%2C11834%2C407%2C5136%2C10054%2C3765%2C1972%2C7970%2C4665%2C7491%2C4345%2C2517%2C10129%2C56%2C518%2C1179%2C5476%2C5839%2C9061%2C4460%2C4232%2C10843%2C74%2C6702%2C2606%2C7704%2C1194%2C1350%2C2987%2C11547%2C3329%2C8166%2C10984%2C10960%2C2191%2C7967%2C6068%2C1921%2C2703%2C11026%2C6081%2C8967%2C10262%2C10718%2C5624%2C9651%2C3458%2C3339%2C2534%2C3222%2C12018%2C4817%2C7606%2C615%2C9664%2C9659%2C1652%2C3588%2C12036%2C6563%2C6542%2C149%2C1599%2C2716%2C5421%2C1943%2C2353%2C4759%2C597%2C7391%2C804%2C8939%2C5043%2C5859%2C4095%2C10561%2C12030%2C115%2C1060%2C1879%2C9756%2C1833%2C4538%2C2745%2C2816%2C10534%2C10476%2C367%2C456%2C11260%2C10829%2C4848%2C7146%2C4502%2C8195%2C10448%2C2485%2C10536%2C81%2C6399%2C1433%2C3569%2C2071%2C8243%2C228%2C8696%2C395%2C9844%2C4983%2C8723%2C1575%2C8281%2C10709%2C6897%2C10071%2C7110%2C2780%2C9487%2C9624%2C713%2C697%2C1042%2C9266%2C7141%2C9701%2C5559%2C4434%2C787%2C3519%2C5759%2C3810%2C7401%2C3312%2C9073%2C1883%2C9780%2C3508%2C3727%2C988%2C4662%2C6508%2C219%2C4277%2C10590%2C820%2C10158%2C9290%2C4028%2C630%2C11807%2C8781%2C5814%2C620%2C9980%2C11005%2C3289%2C3473%2C9846%2C9699%2C4641%2C4076%2C160%2C2884%2C1533%2C10442%2C11337%2C7572%2C1568%2C7956%2C2046%2C2763%2C3511%2C7490%2C9513%2C2402%2C6250%2C5093%2C5889%2C171%2C3050%2C8077%2C4661%2C6447%2C3413%2C9172%2C3773%2C11945%2C1377%2C7194%2C11252%2C11018%2C3389%2C6881%2C2055%2C1889%2C1439%2C11312%2C1542%2C5675%2C2872%2C3787%2C9546%2C2375%2C10736%2C4644%2C11879%2C11947%2C538%2C6271%2C973%2C9041%2C3969%2C9394%2C1274%2C9490%2C9914%2C7436%2C7492%2C10241%2C8825%2C9725%2C9065%2C3294%2C6669%2C6554%2C2183%2C9743%2C3293%2C4744%2C9548%2C5679%2C6748%2C11378%2C3876%2C414%2C9952%2C1284%2C8549%2C8522%2C7983%2C5396%2C8139%2C9613%2C6044%2C3406%2C10697%2C10285%2C2549%2C4118%2C5481%2C1167%2C11135%2C2581%2C7738%2C4407%2C7195%2C10686%2C1594%2C11503%2C8461%2C5239%2C520%2C8359%2C8748%2C4053%2C6424%2C10957%2C4872%2C11866%2C3170%2C5231%2C2829%2C9737%2C8405%2C4809%2C1538%2C2317%2C2990%2C491%2C2275%2C10754%2C1988%2C5411%2C3220%2C9053%2C2123%2C1057%2C8072%2C6005%2C63%2C6375%2C9836%2C1231%2C11402%2C8023%2C3968%2C11592%2C8813%2C2265%2C9545%2C6958%2C5029%2C9758%2C2168%2C9015%2C6513%2C7732%2C9720%2C8778%2C1448%2C7965%2C9530%2C4455%2C11236%2C8252%2C7039%2C1331%2C10574%2C1012%2C3509%2C7663%2C6871%2C1347%2C7351%2C9176%2C10796%2C7960%2C2334%2C1252%2C9843%2C2411%2C2242%2C7501%2C1381%2C694%2C3801%2C6464%2C6706%2C11556%2C9046%2C1407%2C10074%2C11845%2C613%2C6341%2C6570%2C10456%2C11131%2C9811%2C9975%2C5275%2C4739%2C11183%2C4841%2C1735%2C6895%2C554%2C3998%2C1445%2C11928%2C10567%2C7617%2C1842%2C9186%2C10644%2C2374%2C5535%2C8303%2C7616%2C9273%2C2719%2C4931%2C4196%2C10817%2C3710%2C9416%2C4862%2C3135%2C8326%2C6126%2C6482%2C1159%2C10027%2C2486%2C6111%2C6061%2C10380%2C744%2C1787%2C10892%2C6754)&format_min=-8.241436004638672&format_max=8.241436004638672&format_palette=%23000000-%23ffffff-%23000000&format_missing=%23d400c2)

Decoded URL

```
https://taco.caleydoapp.org/api/dataset/matrix/tcgaGbm20130222Mrna/data?format=png&range=(0:2,3,12,14:18,19:22,24:32,37:39,43,45,46,49,50:52,73,83,85,88,89:91,96,101,102:104,105,108,110:112,113:115,119,122,123,127,128,133,137:141,142:145,146,148,158,160,162,165:168,169:171,177,183,185:187,189,191,203,207,209,215,227,233,241:243,248:252,253,260,267,268:270,277:282,287,291,292,296,297,299,300,320,321:323,325,329,335:337,340,350,353:355,369,372,374,384,388,392,395,400,406,411,416,427:429,430,441,443,445,449:452,457:459,460,462,465,467,470,479,483:486,487:489,490:492,493,496,497,500,508:511,523:525,2,4,5:8,9,11,13,18,22,23,33,36,48,53,55,58,60,61,66,74:76,84,86,126,129,156,161,163:165,171,174,178,187,188,196,204,210,213,217,223,225,234,256,261,265,274,285:287,305,309,310,313,319,330,332:334,341:344,347:350,351,357,358,363,367,389,390,401,412,423,424:427,439:441,452,466,468:470,471:473,477,494,502,511,516,518,519:522,525,8,10,32,34:36,40,47,52,57,59,62,63:66,72,76,77,87,91:93,99,106,109,112,115,116,132,134:136,145,147,150,157,159,172,173,175,179:183,198:203,206,211,212,216,220,222,224,235:240,243,246,252,254,255,257,259,262:265,270:272,273,275,276,282,288,290,294,295,298,302,306,307,311,312,315,316:319,323:325,326,331,334,338,346,355,359,361,370,373,375:377,378,381,383,385,391,394,396:400,402,404,405,407,408:411,413:415,417:419,420,422,429,431,433,435,436,442,444,448,453,455,456,473,474:477,480:482,486,489,492,495,501,504,507,513:516,517,526,527,39,41:43,44,54,56,67,68:72,78:83,93:96,97:99,100,104,107,117,118,120,121,124,125,130,131,136,141,149,151,152:156,168,176,184,190,192,193:196,197,205,208,214,218:220,221,226,228:233,240,244,245,247,258,266,272,283,284,289,293,301,303:305,308,314,327:329,337,339,344:346,352,356,360,362,364,365:367,368,371,377,379,380,382,386:388,393,403,415,419,421,432,434,437,438,446,447,454,459,461,463,464,478,482,498,499,503,505:507,512,522),(11772,8709,2723,10376,659,6549,2586,9532,8477,1710,9205,5517,7151,5857,1891,10190,5024,10275,5626,7818,9850,1273,8717,7277,10394,11409,11404,2428,267,10924,7545,9334,3549,1412,5827,10202,5146,4762,11608,9294,7637,6907,7058,4133,6445,2736,1560,631,4293,2562,8587,2628,3403,10807,1844,8176,3845,9231,6778,3751,5335,9142,1425,7566,6929,939,9621,11761,11558,1304,11255,1856,10917,4910,6691,854,7395,3779,1431,7945,5982,1576,8584,10876,3162,2247,3848,8227,11626,6324,1485,9544,2383,11221,4428,8220,10677,495,9567,3982,11052,7825,1604,5153,738,11670,3089,11514,8702,9331,678,841,6228,5757,3908,6555,11273,1215,2462,1508,4158,1389,11586,1192,3901,3598,11482,8004,2890,5228,1956,5904,8660,7056,7434,6183,8095,2223,11510,4971,10933,3297,9666,9210,3272,2479,4115,2114,9806,7847,7346,2246,2422,4310,3399,4525,9462,6589,6469,3438,10928,2747,8769,8648,1607,2201,113,10459,6632,10022,12028,6971,1245,11331,5091,10302,5389,647,5818,9619,7708,935,3864,5185,3769,7629,7167,990,5121,8567,3380,10034,1268,10809,2416,5237,1595,5713,4301,4011,4452,5691,11093,7533,5600,9070,11883,6280,6421,3091,8009,2179,542,11621,2204,1380,1478,7103,4194,3856,2860,10379,10682,6618,6928,5715,3213,7327,4223,8564,4105,11270,6749,1035,8395,5004,10791,11528,9321,8474,3217,5252,8060,2663,7278,7180,6904,7384,7129,11256,7701,11259,8274,5450,4962,114,618,2666,11878,3587,2050,2316,2919,7938,11908,8257,2848,6685,1573,10654,4732,1765,9661,6264,9690,1608,3357,345,7530,4144,7018,11315,409,6470,2319,7305,11786,2170,2918,6064,4364,9220,8698,6523,3314,2064,8944,10614,1890,7485,8731,7588,2758,72,9312,7745,8439,7354,11092,3319,11977,11800,7946,9728,3792,7547,8193,5109,3539,4251,8826,4605,7947,11284,6309,8544,6146,3600,2962,9095,9098,11965,7288,8679,3353,5838,8668,51,4953,863,1306,421,5856,4146,3691,49,7366,6954,3127,9064,853,6203,6694,8070,2382,8793,2535,7019,1067,6010,1600,1593,10257,8040,3899,11973,7914,692,5008,680,993,2766,2177,9657,6977,5090,9789,11529,3012,8756,11641,296,3130,7097,9181,9586,832,5198,2005,6174,9951,2567,11162,4049,6282,3501,8037,7433,6312,4823,7808,11750,9388,3711,11019,11733,6443,6665,8956,6926,3006,3141,11497,193,11968,176,8792,8152,9620,2233,5570,10422,9726,9279,1990,11067,5599,8021,10343,281,10980,4303,4895,6530,10539,11899,11912,9410,4539,3384,9027,11444,8171,2118,9208,5341,7289,2986,5954,8708,6209,2530,10064,10296,4492,8886,8075,3278,3893,3440,716,11101,5177,9805,11225,5621,9581,5489,11700,11483,4519,3377,2305,8239,4472,8771,10869,1929,8514,11024,5892,8420,6806,6697,7881,366,10150,1711,9969,822,9001,480,8531,11635,7754,3407,5115,653,9019,5919,135,7177,8088,600,1982,5127,4646,6781,2741,6531,7479,3446,8875,2642,3392,11208,4927,10815,1501,6331,8845,2025,3911,9675,6273,4305,10717,11212,1780,3975,435,10992,3759,6591,1464,10231,10191,4035,128,3076,11300,1741,7595,5837,6847,9820,5923,240,11649,646,11891,5311,5511,7564,6367,11858,1963,9315,3057,5730,10348,2675,7603,3311,5798,11931,3439,1314,10013,2359,4191,9399,5815,10080,926,9342,1702,5732,5473,5536,6836,9379,9303,2152,10545,936,2404,8136,5802,7926,8938,5903,4240,4598,436,3833,2339,11904,2126,5488,2997,4618,11847,4906,10423,493,7092,2205,894,4821,8749,10731,5741,6556,104,11096,4839,7633,736,5431,4351,2808,1203,1294,9925,3923,5601,6501,1328,2563,4273,8348,11294,1547,9712,1495,11283,6427,10331,10652,6075,10140,4995,10579,8585,1091,11911,10832,3609,6163,1056,5787,8596,6655,1090,1341,2110,1649,7333,4117,1367,2200,5151,10314,968,5861,8212,7306,904,1853,8715,8962,7715,9129,10116,2620,4797,11979,5993,7330,1456,4639,2401,1316,7299,701,3442,5283,10159,7237,6579,9736,1545,10994,3737,5071,5816,2299,9075,3999,9600,5656,5143,7877,3410,1668,10831,11108,1059,5625,3209,10072,2193,8779,2721,3789,3970,8206,731,3251,5382,11115,9146,9485,5271,5944,9427,10566,1934,10060,9721,207,11540,8149,4668,1699,10953,3855,9760,1707,2335,9398,11754,8181,8392,9894,11960,10974,8758,9283,569,8645,10167,5521,5025,3239,7140,7599,2487,11578,1044,9755,937,4529,3767,3917,3889,768,5547,9655,5414,2536,8985,9680,3900,4737,9317,3020,48,8237,11342,7081,11759,10487,4770,4069,265,4337,9913,6612,10028,5053,8096,511,4530,1135,6766,8110,9852,9343,9305,12013,3503,10108,1539,4029,508,9372,10194,7166,4464,2906,1897,6365,2096,4774,1520,6583,4629,3871,1269,786,7246,2458,5131,1802,6142,2681,4016,2988,9930,2116,9341,2288,4382,38,11687,10921,6096,8155,9213,1250,2117,3126,9077,2613,4228,5526,2775,1992,7374,6727,1150,8214,119,11555,2671,749,10321,2347,445,8271,652,10272,2187,3260,8289,172,5060,3713,8807,7205,7297,11502,5977,3146,1117,5707,6316,6208,9568,3657,570,252,6487,11943,6067,6805,1236,8666,9376,6276,548,781,7990,8506,9800,6803,10977,2490,4311,708,1534,10256,3983,7578,3948,735,3497,6094,2992,8373,6664,886,4926,6259,5157,2977,10997,1642,16,9866,7014,11791,8991,3788,1410,1120,1395,11140,833,11405,5039,11099,1886,3599,10801,3137,11704,7611,2868,3072,9361,10858,10602,4825,10253,4950,9986,298,11083,5953,6944,10304,2105,8776,9703,3806,9043,11709,2481,5563,903,8669,9961,449,7128,10550,5408,9310,1704,2912,4518,9131,2943,163,7030,11226,10488,10029,11632,604,1270,6620,5101,2035,9097,3839,721,10375,3184,5725,3366,8434,5524,2293,4989,7188,9049,2715,10222,8483,9392,6597,2080,6951,8606,11048,8356,777,6047,1797,5291,4533,10860,4045,8943,4932,7231,8959,1325,3004,167,9768,9630,8357,4968,5947,900,8454,11037,7977,5968,883,7961,5568,1409,1824,255,1237,10568,7206,3187,6001,9438,3828,4066,10512,3870,481,9265,3432,4198,1563,5949,4355,11190,10519,6771,7794,7471,9693,5047,2391,10465,4645,8290,4591,4339,9407,6256,919,10365,4114,2709,9761,4445,7192,11383,5385,2738,2847,8464,3854,225,6690,5527,10897,8068,8574,11441,964,7435,7093,8829,11243,11332,4005,5002,6071,2955,6745,4458,217,507,2393,11808,3880,6268,7623,11834,407,5136,10054,3765,1972,7970,4665,7491,4345,2517,10129,56,518,1179,5476,5839,9061,4460,4232,10843,74,6702,2606,7704,1194,1350,2987,11547,3329,8166,10984,10960,2191,7967,6068,1921,2703,11026,6081,8967,10262,10718,5624,9651,3458,3339,2534,3222,12018,4817,7606,615,9664,9659,1652,3588,12036,6563,6542,149,1599,2716,5421,1943,2353,4759,597,7391,804,8939,5043,5859,4095,10561,12030,115,1060,1879,9756,1833,4538,2745,2816,10534,10476,367,456,11260,10829,4848,7146,4502,8195,10448,2485,10536,81,6399,1433,3569,2071,8243,228,8696,395,9844,4983,8723,1575,8281,10709,6897,10071,7110,2780,9487,9624,713,697,1042,9266,7141,9701,5559,4434,787,3519,5759,3810,7401,3312,9073,1883,9780,3508,3727,988,4662,6508,219,4277,10590,820,10158,9290,4028,630,11807,8781,5814,620,9980,11005,3289,3473,9846,9699,4641,4076,160,2884,1533,10442,11337,7572,1568,7956,2046,2763,3511,7490,9513,2402,6250,5093,5889,171,3050,8077,4661,6447,3413,9172,3773,11945,1377,7194,11252,11018,3389,6881,2055,1889,1439,11312,1542,5675,2872,3787,9546,2375,10736,4644,11879,11947,538,6271,973,9041,3969,9394,1274,9490,9914,7436,7492,10241,8825,9725,9065,3294,6669,6554,2183,9743,3293,4744,9548,5679,6748,11378,3876,414,9952,1284,8549,8522,7983,5396,8139,9613,6044,3406,10697,10285,2549,4118,5481,1167,11135,2581,7738,4407,7195,10686,1594,11503,8461,5239,520,8359,8748,4053,6424,10957,4872,11866,3170,5231,2829,9737,8405,4809,1538,2317,2990,491,2275,10754,1988,5411,3220,9053,2123,1057,8072,6005,63,6375,9836,1231,11402,8023,3968,11592,8813,2265,9545,6958,5029,9758,2168,9015,6513,7732,9720,8778,1448,7965,9530,4455,11236,8252,7039,1331,10574,1012,3509,7663,6871,1347,7351,9176,10796,7960,2334,1252,9843,2411,2242,7501,1381,694,3801,6464,6706,11556,9046,1407,10074,11845,613,6341,6570,10456,11131,9811,9975,5275,4739,11183,4841,1735,6895,554,3998,1445,11928,10567,7617,1842,9186,10644,2374,5535,8303,7616,9273,2719,4931,4196,10817,3710,9416,4862,3135,8326,6126,6482,1159,10027,2486,6111,6061,10380,744,1787,10892,6754)&format_min=-8.241436004638672&format_max=8.241436004638672&format_palette=#000000-#ffffff-#000000&format_missing=#d400c2
```

### Observed behavior

* No heatmap is shown
* Flask returns a [431 HTTP error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431) _431 Request Header Fields Too Large_

### Expected behavior

* If the URL is too long the arguments should be send as POST request instead of GET request
* Similar implementation can be found in [tdp_core/src/rest.ts](https://github.com/datavisyn/tdp_core/blob/c148309352440b2e8386e2549f3e30ae68897139/src/rest.ts#L75-L90)

### PR DESCRIPTION
**Pull request by dvvanessastoiber**
Fixes #69
Requires https://github.com/phovea/phovea_server/pull/83, https://github.com/phovea/phovea_core/pull/149

If the range parameter is too large (and results in a too long URL) the POST method is used to get the heatmap image. An URL is considered too long when it has more than 4096 characters.

image

image

The implementation is similar to [tdp_core data loading](https://github.com/datavisyn/tdp_core/blob/d8216da36070e7464b7273db72d3c59f852f0d91/src/rest.ts#L75-L90).

### CODE REVIEW

File: src/heatmap/HeatMapImageRenderer.ts [hunk 1]
```diff
@@ -18,6 +20,8 @@ function ensureHex(color: string) {
   return `#${toHex(rgb.r)}${toHex(rgb.g)}${toHex(rgb.b)}`;
 }
 
+const TOO_LONG_URL = 4096;
```
Comment (dg-datavisyn) [inline src/heatmap/HeatMapImageRenderer.ts]: Name is a little bit misleading. 4096 is not too long - 4097 would be. I would call it something TDP_URL_LENGTH_LIMIT or MAX_URL_LENGTH

Also your check in line 145 says `>` and not `>=`

File: src/heatmap/HeatMapImageRenderer.ts [hunk 2]
```diff
@@ -130,11 +134,47 @@ export default class HeatMapImageRenderer extends AHeatMapCanvasRenderer impleme
...
+
+    const encoded = encodeParams(params);
+    if (encoded && (url.length + encoded.length > TOO_LONG_URL)) {
+      // use post instead
+      sendAPI(url, params, 'POST', 'blob').then((image) => {
+        const imageURL = window.URL.createObjectURL(image);
+        this.image.src = imageURL;
+      });
+    } else {
+      this.image.src = data.heatmapUrl(all(), args);
```
Comment (dg-datavisyn) [inline src/heatmap/HeatMapImageRenderer.ts:151]: This is also called when `encoded` results to `false` no matter how long the URL is. Is this intended?

File: src/heatmap/HeatMapImageRenderer.ts [hunk 3]
```diff
@@ -130,11 +134,47 @@ export default class HeatMapImageRenderer extends AHeatMapCanvasRenderer impleme
...
+    }
 
     super.buildSelection(data, $root, scale);
 
     return $root;
+  }
+}
 
+function prepareParameter(range: Range, options: IHeatMapUrlOptions) {
+  const args: any = {
```
Comment (dg-datavisyn) [inline src/heatmap/HeatMapImageRenderer.ts]: is there a typing for the args?

File: src/heatmap/HeatMapImageRenderer.ts (hunk 2 above)
Comment (dvvanessastoiber) [reply src/heatmap/HeatMapImageRenderer.ts:151]: the function `encodeParams(data: any = null)` returns a string, therefore encoded can only be empty, `null` or a string

Comment (dg-datavisyn) [reply src/heatmap/HeatMapImageRenderer.ts:151]: But in the if statement you write `if (encoded && (url.length + encoded.length > TOO_LONG_URL)) {` when `encoded === False` then automatically choose the GET option even if the url is longer than 4096. Is this intended?

**Comment by dvvanessastoiber** [comment]
TODO: change import for `MAX_URL_LENGTH` in _HeatMapImageRenderer.ts_ when PR https://github.com/phovea/phovea_core/pull/150 is merged

File: src/heatmap/HeatMapImageRenderer.ts (hunk 1 above)
Comment (thinkh) [reply src/heatmap/HeatMapImageRenderer.ts]: We extracted this constant to phovea_core with PR phovea/phovea_core#150

File: src/heatmap/HeatMapImageRenderer.ts (hunk 3 above)
Comment (thinkh) [reply src/heatmap/HeatMapImageRenderer.ts]: We added them with PR phovea/phovea_core#150

**Review by thinkh — APPROVED** [review]
Looks good
